### ISSUE TITLE
check-ping false positives

### ISSUE THREAD

**Issue by AirCombat** [sensu-plugins/sensu-plugins-network-checks#34] opened 2016-04-19 09:14 UTC
Check-ping gives constant false positives. I ping a number of servers on a number of different networks including 8.8.8.8

The checks fail and then the following check always succeeds. The check that fails always says none successful. When pinging during this period from bash, no packets are lost.

CheckPING CRITICAL: ICMP ping unsuccessful for host: 10.1.8.1 (successful: 0/20)
CheckPING CRITICAL: ICMP ping unsuccessful for host: 10.1.8.2 (successful: 0/3)

The following is an example where sensu gave a critical and then a ok alert during the pings below:

[root@sensu ~]# ping 10.1.8.1 -i 0.1 -c 2000
--- 10.1.8.1 ping statistics ---
2000 packets transmitted, 2000 received, 0% packet loss, time 200026ms
rtt min/avg/max/mdev = 0.185/0.330/0.948/0.202 ms

Thanks

**Comment by eheydrick** [comment] 2016-05-09 19:47
Hi @AirCombat, what is the platform and full check command you are running? Trying to repro but so far unable to.

**Comment by eheydrick** [comment] 2016-06-14 17:59
Were you able to dig more?

**Comment by AirCombat** [comment] 2016-06-14 18:08
Hi,

Apologies for the slow response.

`
    "Ping_HG_Router": {
      "command": "check-ping.rb -h 192.168.1.4 -c 8 -W 0.1 -C 0 -T 10",
      "interval": 175,
        "handlers": ["OnCallSupport"],
      "standalone": true
    }`

This is on CentOS 7.2  (1511), ruby 2.3.0p0, Sensu 0.25

**Comment by kai101** [comment] 2016-07-20 02:59
the issue is on 3103dc3e3b147cc014bbbff1c868e7d785ede81f

**Comment by eheydrick** [comment] 2016-08-01 06:06
@AirCombat can you try @kai101's fix in #41 that was just merged to master. If it looks good I'll cut a new release.

**Comment by eheydrick** [comment] 2016-08-07 23:22
Released in 1.1.0.

**Closed by eheydrick** 2016-08-07 23:22 UTC
